title: huk-wiki
description: 안녕하세요. 허리업 코리아 위키 입니다.
show_downloads: false
comments: false
logo_url: CI.png
google_analytics:
git_branch: master
theme: 
use_github_wiki: false
use_prose_io: true
google_cse_token: 
custom_sidebar: false
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
